version: '3.8'

services:
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Graphiti expects the standard NEO4J_* variables; translate them to
      # Neo4j's expected format here. The password is pulled from .env.
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme123}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7687:7687"   # Bolt
      - "7474:7474"   # HTTP UI
    volumes:
      - neo4j_data:/data
