version: '3.8'

services:
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme123}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

    # <-- publish these ports externally
    ports:
      - "7474:7474"   # Neo4j HTTP UI
      - "7687:7687"   # Bolt protocol

    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
