services:
  neo4j:
    image: neo4j:5.26
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme123}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # “Expose” Neo4j's HTTP port through Coolify:
      - SERVICE_FQDN_NEO4J_7474=/
      - SERVICE_URL_NEO4J_7474
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
